apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: mcp-ws-service
spec:
  definition:
    title: Model Context Protocol WebSocket Service
    description: >-
      Provides an MCP (Model Context Protocol) endpoint over WebSocket plus auxiliary HTTP
      endpoints for health checks, server-sent stream, and server notifications broadcasting.
      Wraps JSON-RPC 2.0 messages and dispatches to MCP processors (initialize, ping, tools/list,
      tools/call, resources/get) while supporting notifications and server push.
    type: object
    properties:
      wsComponent:
        title: WebSocket Component
        description: Camel WebSocket component to use (e.g., platform-websocket or undertow).
        type: string
        default: undertow    
      wsHost:
        title: WebSocket Host
        description: Host/interface for the WebSocket endpoint.
        type: string
        default: 0.0.0.0
      wsPort:
        title: WebSocket Port
        description: Port for the WebSocket endpoint.
        type: integer
        default: 8090
      wsPath:
        title: WebSocket Path
        description: Path for the MCP WebSocket (no trailing slash).
        type: string
        default: /mcp
      toolsCallBean:
        title: Tools Call Bean
        description: Bean that handles tools/call requests.
        type: string
        default: sampleToolCallProcessor
      resourcesGetBean:
        title: Resources Get Bean
        description: Bean that handles resources/get requests.
        type: string
        default: mcpResourcesGet
  dependencies:
    - "camel:{{wsComponent}}"
    - "camel:undertow"
    - "camel:bean"
  template:
    beans:
      - name: mcpJsonRpcEnvelope
        type: io.dscope.camel.mcp.processor.McpJsonRpcEnvelopeProcessor
      - name: mcpInitialize
        type: io.dscope.camel.mcp.processor.McpInitializeProcessor
      - name: mcpPing
        type: io.dscope.camel.mcp.processor.McpPingProcessor
      - name: mcpToolsList
        type: io.dscope.camel.mcp.processor.McpToolsListProcessor
      - name: mcpResourcesGet
        type: io.dscope.camel.mcp.processor.McpResourcesGetProcessor
      - name: mcpResourcesList
        type: io.dscope.camel.mcp.processor.McpResourcesListProcessor
      - name: mcpResourcesRead
        type: io.dscope.camel.mcp.processor.McpResourcesReadProcessor
      - name: mcpStream
        type: io.dscope.camel.mcp.processor.McpStreamProcessor
      - name: mcpHealthStatus
        type: io.dscope.camel.mcp.processor.McpHealthStatusProcessor
      - name: mcpNotification
        type: io.dscope.camel.mcp.processor.McpNotificationProcessor
      - name: mcpNotificationsInitialized
        type: io.dscope.camel.mcp.processor.McpNotificationsInitializedProcessor
      - name: mcpNotificationAck
        type: io.dscope.camel.mcp.processor.McpNotificationAckProcessor
      - name: mcpError
        type: io.dscope.camel.mcp.processor.McpErrorProcessor
      - name: mcpRateLimit
        type: io.dscope.camel.mcp.processor.McpRateLimitProcessor
      - name: mcpRequestSizeGuard
        type: io.dscope.camel.mcp.processor.McpRequestSizeGuardProcessor
      - name: mcpUiSessionRegistry
        type: io.dscope.camel.mcp.service.McpUiSessionRegistry
      - name: mcpUiInitialize
        type: io.dscope.camel.mcp.processor.McpUiInitializeProcessor
      - name: mcpUiMessage
        type: io.dscope.camel.mcp.processor.McpUiMessageProcessor
      - name: mcpUiUpdateModelContext
        type: io.dscope.camel.mcp.processor.McpUiUpdateModelContextProcessor
      - name: mcpUiToolsCall
        type: io.dscope.camel.mcp.processor.McpUiToolsCallProcessor
      - name: mcpUiToolsCallPost
        type: io.dscope.camel.mcp.processor.McpUiToolsCallPostProcessor
    from:
      uri: "{{wsComponent}}:ws://{{wsHost}}:{{wsPort}}{{wsPath}}?sendToAll=false&allowedOrigins=*&exchangePattern=InOut"
      steps:
        - process: { ref: mcpRequestSizeGuard }
        - process: { ref: mcpRateLimit }
        - doTry:
            steps:
              - to: "bean:mcpJsonRpcEnvelope"
              - log:
                  loggingLevel: DEBUG
                  message: "WebSocket received: ${body}"
              - choice:
                  when:
                    - simple: "${exchangeProperty.mcp.jsonrpc.type} == 'NOTIFICATION'"
                      steps:
                        - to: "bean:mcpNotification"
                        - log:
                            loggingLevel: INFO
                            message: "Notification: ${exchangeProperty[mcp.notification.type]}"
                        - stop: {}
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'initialize'"
                      steps:
                        - to: mcpInitialize
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'ping'"
                      steps:
                        - to: mcpPing
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'tools/list'"
                      steps:
                        - to: mcpToolsList
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'tools/call'"
                      steps:
                        - to: "bean:{{toolsCallBean}}"
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'resources/list'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP Resources List request received"
                        - to: mcpResourcesList
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'resources/read'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP Resources Read request received"
                        - to: mcpResourcesRead
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'resources/get'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP Resources Get request received"
                        - to: "bean:{{resourcesGetBean}}"
                    # MCP Apps Bridge (ui/*) methods
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'ui/initialize'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP UI Initialize request received"
                        - to: "bean:mcpUiInitialize"
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'ui/message'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP UI Message request received"
                        - to: "bean:mcpUiMessage"
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'ui/update-model-context'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP UI Update Model Context request received"
                        - to: "bean:mcpUiUpdateModelContext"
                    - simple: "${exchangeProperty[mcp.jsonrpc.method]} == 'ui/tools/call'"
                      steps:
                        - log:
                            loggingLevel: INFO
                            message: "MCP UI Tools Call request received"
                        - doTry:
                            steps:
                              - to: "bean:mcpUiToolsCall"
                              - to: "bean:{{toolsCallBean}}"
                              - to: "bean:mcpUiToolsCallPost"
                            doCatch:
                              - exception:
                                  - java.lang.Exception
                                steps:
                                  - to: "bean:mcpUiToolsCallPost"
                                  - setProperty:
                                      name: mcp.error.code
                                      constant: "-32603"
                                  - setProperty:
                                      name: mcp.error.message
                                      simple: "UI tool execution failed: ${exception.message}"
                                  - process:
                                      ref: mcpError
                  otherwise:
                    steps:
                      - setProperty: { name: mcp.error.code, constant: "-32601" }
                      - setProperty:
                          name: mcp.error.message
                          simple: "Unsupported MCP method: ${exchangeProperty[mcp.jsonrpc.method]}"
                      - process: { ref: mcpError }
            doCatch:
              - exception:
                  - java.lang.IllegalArgumentException
                steps:
                  - setProperty:
                      name: mcp.error.code
                      constant: "-32600"
                  - setProperty:
                      name: mcp.error.message
                      simple: "${exception.message}"
                  - process:
                      ref: mcpError
        - choice:
            when:
              - simple: "${header.Content-Type} == null"
                steps:
                  - setHeader: { name: Content-Type, constant: application/json }
        - convertBodyTo: { type: java.lang.String }
        - log:
            loggingLevel: DEBUG
            message: "WebSocket returning: ${body}"
        - setHeader: { name: CamelWebSocketSendToAll, constant: "false" }
        - to: "{{wsComponent}}:ws://{{wsHost}}:{{wsPort}}{{wsPath}}"
    
