name: Build and Test Camel MCP Component

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

      - name: Run tests
        run: mvn test --file pom.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcp-test-results
          path: target/surefire-reports/
