name: Release to Maven Central

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and deploy to Maven Central
        run: |
          mvn -B clean deploy -DskipTests             -P release             -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}             --settings .github/maven-settings.xml

      - name: Upload JAR artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: camel-mcp-release-jars
          path: target/*.jar
